openapi: 3.0.0
info:
    title: FlowersAPI specification
    version: 1.0.0
components:
    schemas:
        User:
            # TODO required, think about Member!
            type: object
            properties:
                Id:
                    type: integer
                Name:
                    type: string
                    minLength:
                    maxLength:
                Login:
                    type: string
                    minLength:
                    maxLength:
                Password:
                    type: string
                    format: password
                    minLength:
                    maxLength:
                CreatedDate:
                    type: string
                    format: date-time
                LoginDate:
                    type: string
                    format: date-time
        Member:
            allOf:
                - $ref: '#/components/schemas/User'
                - type: object
                  properties:
                      GreenHouse:
                          $ref: '#/components/schemas/GreenHouse'
                      GreenHouseName:
                          type: string
                          minLength:
                          maxLength:
                      role:
                          $ref: '#/components/schemas/GreenHouseRole'
        Collection:
            type: array
            items:
                $ref: '#/components/schemas/GreenHouse'
        GreenHouse:
            type: object
            properties:
                Id:
                    type: integer
                Plants:
                    type: array
                    items:
                        $ref: '#/components/schemas/Plant'
                Members:
                    type: array
                    items:
                        $ref: '#/components/schemas/Member'
                CreatedDate:
                    type: string
                    format: date-time
        GreenHouseRole:
            type: string
            enum: # TODO add roles
                - s
        Plant:
            type: object
            properties:
                Id:
                    type: integer
                Name:
                    type: string
                    minLength:
                    maxLength:
                CreatedDate:
                    type: string
                    format: date-time
                LastWaterDate:
                    type: string
                    format: date-time
                NextWaterDate:
                    type: string
                    format: date-time
                Species:
                    $ref: '#/components/schemas/PlantSpecies'
        PlantGroup:
            type: string
            enum:
                - s
        PlantSpecies:
            type: object
            properties:
                SpeciesName:
                    type: string
                    enum:
                        -
                Group:
                    $ref: '#/components/schemas/PlantGroup'
    responses:
    requestBodies:
paths:
    /user:
        post:
            summary: Registration of new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
    /user/login:
        post:
            summary: Login user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
    /user/{userId}:
        get:
            summary: Get information about user
            parameters:
              - in: path
                name: userId
                description: User id
                required: true
                schema:
                    type: integer
        post:
            summary: Update user information
            parameters:
              - in: path
                name: userId
                description: User id
                required: true
                schema:
                    type: integer
            requestBody:
                content: 
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
        delete:
            summary: Delete user
            parameters:
              - in: path
                name: userId
                description: User id
                schema:
                    type: integer

    /user/{userId}/collection:
        get:
            summary: Return user's collection (aka list of user's greenhouses)
            parameters:
              - in: path
                name: userId
                description: User id
                schema:
                    type: integer
        post:
            summary: Create new greenhouse in user's collection
            parameters:
              - in: path
                name: userId
                description: User id
                schema:
                    type: integer
            requestBody:
                content: 
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GreenHouse'
        delete:
            summary: Delete greenhouse from user's collection
            parameters:
              - in: path
                name: userId
                description: User id
                schema:
                    type: integer

    /greenhouse/{grHouseId}?userId=:
        get:
            summary: Return greenhouse information with it's name for user
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer

              - in: query
                name: userId
                description: User Id
                schema:
                    type: integer
        post:
            summary: Update name of greenhouse for user
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer

              - in: path
                name: userId
                description: User Id
                schema:
                    type: integer
            requestBody:
                content: 
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GreenHouse'

    /greenhouse/{grHouseId}/members:
        get:
            summary: Return list of members (users with their greenhouse roles)
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer
    /greenhouse/{grHouseId}/members/{userId}:
        get:
            summary: Return member in greenhouse
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer

              - in: path
                name: userId
                description: User Id
                schema:
                    type: integer
        post:
            summary: Update member role in greenhouse
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer

              - in: path
                name: userId
                description: User Id
                schema:
                    type: integer
            requestBody:
                content: 
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Member'
        delete:
            summary: Delete member from
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer

              - in: path
                name: userId
                description: User Id
                schema:
                    type: integer
    /greenhouse/{grHouseId}/plants:
        get:
            summary: Return list of plants in greenhouse
            parameters:
              - in: path
                name: grHouseId
                description: Greenhouse Id
                schema:
                    type: integer
    /plant/{plId}:
        get:
            summary: Return information about plant
            parameters:
              - in: path
                name: plId
                description: Plant Id
                schema:
                    type: integer
        post:
            summary: Update information about plant
            parameters:
              - in: path
                name: plId
                description: Plant Id
                schema:
                    type: integer
            requestBody:
                content: 
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Plant'
        delete:
            summary: Delete plant in greenhouse
            parameters:
              - in: path
                name: plId
                description: Plant Id
                schema:
                    type: integer
    /plant/{plId}/water:
        get:
            summary: Return last and next dates for water
            parameters:
              - in: path
                name: plId
                description: Plant Id
                schema:
                    type: integer
        post:
            summary: Change last date water
            parameters:
              - in: path
                name: plId
                description: Plant Id
                schema:
                    type: integer
            requestBody:
                content: 
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Plant'